#!/bin/sh


#export JVM_FLAGS="-server -Xmx1G"
#export APOLLO_OPTS="-ea"
#export APOLLO_DEBUG="true"
#export APOLLO_PROFILE="true"
#export JMX_OPTS="-Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

if [ -z "$APOLLO_BASE" ] ; then

  ## resolve links - $0 may be a link to apollo's home
  PRG="$0"
  progname=`basename "$0"`
  saveddir=`pwd`

  # need this for relative symlinks
  dirname_prg=`dirname "$PRG"`
  cd "$dirname_prg"

  while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '.*/.*' > /dev/null; then
    PRG="$link"
    else
    PRG=`dirname "$PRG"`"/$link"
    fi
  done

  APOLLO_BASE=`dirname "$PRG"`
  cd "$saveddir"

  # make it fully qualified
  APOLLO_BASE=`cd "$APOLLO_BASE/.." && pwd`
  export APOLLO_BASE
    
fi

if [ -z "$APOLLO_HOME" ] ; then
  APOLLO_HOME=/opt/twtpush-1.7.1
fi

if [ -f "${APOLLO_BASE}/etc/apollo.profile" ] ; then
  . "${APOLLO_BASE}/etc/apollo.profile"
fi

exec $APOLLO_HOME/bin/apollo $@

